// Code generated by goctl. DO NOT EDIT.
package types

type UserCreateReq struct {
	NickName string `json:"name"`
	Mobile   string `json:"mobile"`
}

type UserCreateResp struct {
	Flag bool `json:"flag"`
}

type UserInfoReq struct {
	UserId int64 `json:"userId"`
}

type UserInfoResp struct {
	UserId   int64  `json:"id"`
	NickName string `json:"name"`
}

type UserUpdateReq struct {
	UserId   int64  `json:"id"`
	NickName string `json:"name"`
}

type UserUpdateResp struct {
	Flag bool `json:"flag"`
}
